dist: trusty
sudo: required

language: scala
scala:
   - 2.11.8
branches:
  only:
    - master

dependencies:
  override:
    - wget https://raw.githubusercontent.com/Sagacify/ci-tools/master/run-sonar.sh
    - chmod +x run-sonar.sh
    - ./run-sonar.sh check
    - ./run-sonar.sh install
  cache_directories:
    - "~/.ivy2"
    - "~/.sbt"

script: 
 - sbt coverage test coveralls
 - ./run-sonar.sh run

addons:
  sonarqube:
    token:
      secure: "KgaU2eWOtRLv+dx6+3/kqOv3vTmKDGw+amWuSP25yDS2J65f0syLo/P3zCFUjUfKESlYa+xBK/IIFMDVClNMKKdc3vJ35xqlBlSap1m4z/VfV3rw0UdrXI5Q8GTIx1ErcMh1t6CLPf/JlLEYPeQwVKnzZdB7+e2u0K3ZxOEwFKX6ZO0EKdSxC/cHFktXK0cd/l6d2qeE+5KmbeWaeAcv/aoPgXCP1D7omscvaQAY7+MS9S3ZWfm7yVAef/MRntrechdHh/Q7HjbxAwdB3MyeeB/iZgO/O0Os0BwKxUY6GF+HR9/idDvjxm9XWzDU2YYx3dg/LPrg9Nw2pXX24y+LtoyYz3vdaxwY3dj8j3naJxes0rFcErC7ZWoMPCA3S9CqvtCQPy/YgXpEth0OksuovvR4TGVTrd0uSiJKhqAMSzt/w5CPhaPzocu7tYv524iS/wZ8Ke/hYFmeF5t5Uf0oJvHmXzgIeDOj/Me/bXdUEgFK5T1CNSXdDJk/9SyA/AZ7LZru+p0D5JXxMFMFINcGEGF/tW0HdzthPWPG8QHPRHg2as+j8BMm3KRKUt6wiV5O6pTB7lTKkWdN3QDs61TJ0fOGv/US5T2VukYmYpcbmTZHuFfRqUAXD1m/bvSF9ry8P/m/cilPF0OJOunvcq90RI6Xr+iv4hDbyJBjFyNzFFY="

jdk:
  - oraclejdk8

cache:
  directories:
    - '$HOME/.sonar/cache'

notifications:
  email: false
