# See http://about.travis-ci.org/docs/user/build-configuration/
language: scala
scala:
   - 2.10.4
   - 2.11.2
branches:
  only:
    - master
notifications:
  email:
    recipients:
- prasinous@gmail.com
